--created with Super_Hugo's Stage Editor v1.6.3
local shadname = "glitchEffect";

function onCreate()
    initLuaShader(shadname)
    
	makeLuaSprite('obj4', 'FullyBreakfast/dish', -350, 335)
	setObjectOrder('obj4', 0)
    scaleObject('obj4', 2.5, 2.5)
	addLuaSprite('obj4', true)
	
	makeLuaSprite('obj5', 'FullyBreakfast/cakes', -4242, -1882)
    setSpriteShader('obj5', shadname)
    setShaderFloat('obj5', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj5', 'uFrequency', 5)
    setShaderFloat('obj5', 'uSpeed', 2)
	setObjectOrder('obj5', 0)
	scaleObject('obj5', 2.6, 2.6)
	addLuaSprite('obj5', true)

	makeLuaSprite('obj6', 'FullyBreakfast/nuggets', -4242, -1882)
    setSpriteShader('obj6', shadname)
    setShaderFloat('obj6', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj6', 'uFrequency', 5)
    setShaderFloat('obj6', 'uSpeed', 2)
	setObjectOrder('obj6', 0)
	scaleObject('obj6', 2.6, 2.6)
	addLuaSprite('obj6', true)
	
	makeLuaSprite('obj7', 'FullyBreakfast/pichis', -4242, -1882)
    setSpriteShader('obj7', shadname)
    setShaderFloat('obj7', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj7', 'uFrequency', 5)
    setShaderFloat('obj7', 'uSpeed', 2)
	setObjectOrder('obj7', 0)
	scaleObject('obj7', 2.6, 2.6)
	addLuaSprite('obj7', true)

	makeLuaSprite('obj8', 'FullyBreakfast/chocolates', -4242, -1882)
    setSpriteShader('obj8', shadname)
    setShaderFloat('obj8', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj8', 'uFrequency', 5)
    setShaderFloat('obj8', 'uSpeed', 2)
	setObjectOrder('obj8', 0)
	scaleObject('obj8', 2.6, 2.6)
	addLuaSprite('obj8', true)

	makeLuaSprite('obj9', 'FullyBreakfast/burger', -4242, -1882)
    setSpriteShader('obj9', shadname)
    setShaderFloat('obj9', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj9', 'uFrequency', 5)
    setShaderFloat('obj9', 'uSpeed', 2)
	setObjectOrder('obj9', 0)
	scaleObject('obj9', 2.6, 2.6)
	addLuaSprite('obj9', true)

	makeLuaSprite('obj10', 'FullyBreakfast/bread', -4242, -1882)
    setSpriteShader('obj10', shadname)
    setShaderFloat('obj10', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj10', 'uFrequency', 5)
    setShaderFloat('obj10', 'uSpeed', 2)
	setObjectOrder('obj10', 0)
	scaleObject('obj10', 2.6, 2.6)
	addLuaSprite('obj10', true)

	makeLuaSprite('obj11', 'FullyBreakfast/cakes', -4242, -1882)
    setSpriteShader('obj11', shadname)
    setShaderFloat('obj11', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj11', 'uFrequency', 5)
    setShaderFloat('obj11', 'uSpeed', 2)
	setObjectOrder('obj11', 0)
	scaleObject('obj11', 2.6, 2.6)
	addLuaSprite('obj11', true)

	makeLuaSprite('obj12', 'FullyBreakfast/nuggets', -4242, -1882)
    setSpriteShader('obj12', shadname)
    setShaderFloat('obj12', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj12', 'uFrequency', 5)
    setShaderFloat('obj12', 'uSpeed', 2)
	setObjectOrder('obj12', 0)
	scaleObject('obj12', 2.6, 2.6)
	addLuaSprite('obj12', true)
	
	makeLuaSprite('obj13', 'FullyBreakfast/pichis', -4242, -1882)
    setSpriteShader('obj13', shadname)
    setShaderFloat('obj13', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj13', 'uFrequency', 5)
    setShaderFloat('obj13', 'uSpeed', 2)
	setObjectOrder('obj13', 0)
	scaleObject('obj13', 2.6, 2.6)
	addLuaSprite('obj13', true)

    makeLuaSprite('obj14', 'FullyBreakfast/chocolates', -4242, -1882)
    setSpriteShader('obj14', shadname)
    setShaderFloat('obj14', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj14', 'uFrequency', 5)
    setShaderFloat('obj14', 'uSpeed', 2)
	setObjectOrder('obj14', 0)
	scaleObject('obj14', 2.6, 2.6)
	addLuaSprite('obj14', true)

	makeLuaSprite('obj15', 'FullyBreakfast/burger', -4242, -1882)
    setSpriteShader('obj15', shadname)
    setShaderFloat('obj15', 'uWaveAmplitude', 0.1)
    setShaderFloat('obj15', 'uFrequency', 5)
    setShaderFloat('obj15', 'uSpeed', 2)
	setObjectOrder('obj15', 0)
	scaleObject('obj15', 2.6, 2.6)
	addLuaSprite('obj15', true)

end

function onUpdatePost(elapsed)
	setShaderFloat('obj5', 'uTime', os.clock())
	setShaderFloat('obj6', 'uTime', os.clock())
	setShaderFloat('obj7', 'uTime', os.clock())
	setShaderFloat('obj8', 'uTime', os.clock())
	setShaderFloat('obj9', 'uTime', os.clock())
	setShaderFloat('obj10', 'uTime', os.clock())
	setShaderFloat('obj11', 'uTime', os.clock())
	setShaderFloat('obj12', 'uTime', os.clock())
	setShaderFloat('obj13', 'uTime', os.clock())
	setShaderFloat('obj14', 'uTime', os.clock())
	setShaderFloat('obj15', 'uTime', os.clock())
end